[release.sagitta]
  latest = "1.4.0"

  security_advisory = [
  ]

  notes = "GA release"

[release.equuleus]
  latest = "1.3.7"

  security_advisory = [
    {cve="CVE-2024-2961", title="GNU libc iconv buffer overflow", description="Potential DoS in any application that encodes strings", status="fixed"},
  ]
