[release.sagitta]
  latest = "1.4.0-epa3"

  security_advisory = [
    {cve="CVE-2024-2961", title="GNU libc iconv buffer overflow", description="Potential DoS in any application that encodes strings", status="fixed"},
  ]

  notes = "Early production access, please report any issues!"

[release.equuleus]
  latest = "1.3.7"

  security_advisory = [
    {cve="CVE-2024-2961", title="GNU libc iconv buffer overflow", description="Potential DoS in any application that encodes strings", status="fixed"},
  ]
